# MoonBoard Holds
## 0. Download and Save Problems

In [ ]:
## Download Problems
import moon.data
cookies = '...'

# 1843 pages as of 12.20.19; save to probs.json
probs = moon.data.download_problems(cookies)
util.write_problems(probs)

## I. Load Problems, Clean Data

In [1]:
import moon.data

probs = moon.data.read_problems(remove_dups=True)
display(probs)

Pruning 61 duplicate probs.


Name Grade UserGrade  UserRating  Repeats  \
2175                      ACG70    6C      None           3        2   
2204                      ACG70    6C      None           3        1   
2299                 L'INSONNIA   6C+      None           0        0   
2300                 L'INSONNIA   6C+      None           0        0   
2499                 STILL DAVE   6B+      None           0        0   
2500                 STILL DAVE   6B+      None           2        3   
4095                  FORSØK 39   6B+       6B+           2       12   
4124                  FORSØK 39   6B+      None           3        2   
5277                     UH-000   6C+      None           3        1   
5278                     UH-000   6C+      None           2        1   
5359                  35 GRADER    7A      None           3        1   
5360                  35 GRADER    7A      None           2        1   
5469             SUMMER CAMP V2   6B+      None           2        3   
5470             SUMMER CAMP V2   6B+       6B+           2       13   
5785                     DAVIDS    7B      None           0        0   
5786                     DAVIDS    7B      None           3        2   
7346              CHRIS PROBLEM    6C      None           3        3   
7347              CHRIS PROBLEM    6C        6C           2        7   
8105             FRANK THE TANK   6B+      None           2        2   
8106             FRANK THE TANK   6B+       6B+           2       13   
8413       DON’T TRY THAT CLIMB    7A      None           3        1   
8414       DON’T TRY THAT CLIMB    7A      None           0        0   
9183              ВСЁ СНАЧАЛА№2   6B+       6B+           2       20   
9184              ВСЁ СНАЧАЛА№2   6B+       6B+           2        8   
9585           ЛЕГХКАЯ ПРОБЛЕМА   6B+      None           1        1   
9586           ЛЕГХКАЯ ПРОБЛЕМА   6B+      None           1        1   
12508                   SNIKERS    7B      None           0        0   
12509                   SNIKERS    7B      None           0        0   
13601                DANG MAGIC    7C      None           0        0   
13602                DANG MAGIC    7C      None           0        0   
14157                    YUMMI!    7B        7B           2       13   
14158                    YUMMI!   7A+      None           3        5   
14288         THE LAST BIG BANG    7A      None           2        1   
14289         THE LAST BIG BANG    7A      None           0        0   
14524  BZ - WALKING ON THE MOON    6C      None           3        4   
14525  BZ - WALKING ON THE MOON    6C      None           3        2   
15207                  DIONYSUS   6B+       6B+           2       10   
15208                  DIONYSUS   6B+       6B+           2        5   
15780                  NOT MINE   6B+       6B+           2        7   
15781                  NOT MINE   6B+      None           2        3   
15782                  NOT MINE   6B+      None           3        3   
15863                       ELY   6B+      None           3        1   
15864                       ELY   6B+      None           0        0   
16528          BEST KEPT SECRET   7A+      None           0        0   
16529          BEST KEPT SECRET   7A+      None           3        1   
16566                  RECEPÇÃO    7B        7B           3        7   
16567                  RECEPÇÃO    7B      None           2        2   
17947            SON OF KRYPTON   6B+       6B+           2        7   
17948            SON OF KRYPTON   6B+      None           2        2   
20532                      MEG1   6B+       6B+           2       13   
20533                      MEG1   6B+       6B+           3        6   
20823              JACK REACHER   7A+      None           0        0   
20824              JACK REACHER   7A+      None           0        0   
21656               PIC A BANIC   7A+      None           3        1   
21657               PIC A BANIC   7A+      None           0        

Name Grade UserGrade  UserRating  Repeats Holds.Start  \
0         ROCHDALE'S FINEST    6C        6C           3       18    [B3, F5]   
1                      CHAD   7B+       7B+           3       82        [C5]   
2                PROBLEM 23    7C        7C           3       88    [D3, B4]   
3                PROBLEM 22   6C+       6C+           3       21        [K5]   
4                PROBLEM 21   7A+      None           3        0    [B4, D3]   
...                     ...   ...       ...         ...      ...         ...   
27609             MAORI BIS   6B+      None           0        0        [F5]   
27610  POOH BEAR IS A DRUNK    6C      None           0        0        [F5]   
27611  I’M YOUR HUCKLEBERRY    6C      None           0        0        [F5]   
27612               MONKERO   6B+      None           0        0        [G4]   
27613   THE SKY’S THE LIMIT   6B+      None           0        0    [K5, I4]   

        Holds.End                                Holds.Others  
0           [B18]                         [C7, E12, D11, E16]  
1           [D18]                     [D7, A9, F11, F13, E16]  
2           [A18]       [F6, G7, K7, K10, G11, J14, F15, D16]  
3           [K18]                    [G8, F10, D12, I13, I16]  
4           [H18]                          [F6, C9, F12, F15]  
...           ...                                         ...  
27609       [D18]                     [E8, F11, C13, E16, G2]  
27610       [H18]                    [C7, D10, C12, F15, E15]  
27611       [D18]                         [E8, I11, F13, H16]  
27612       [G18]           [G6, J8, H11, G11, E13, E15, D17]  
27613  [B18, C18]  [F5, B4, E8, B16, C13, E11, E15, A10, A13]  

[27614 rows x 8 columns]

## II. Count some stuff

In [22]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000)

array = moon.data.problems_to_array(probs)
counts_bytype = np.sum(array, axis=0)
counts = np.sum(counts_bytype[:,:,[0,1,2]], axis=-1)

In [34]:
usage_bytype = counts_bytype.astype(np.float32)
for i in range(0, 4):
    usage_bytype[:,:,i] /= np.sum(usage_bytype[:,:,i])

display(usage_bytype[:,:,0])  # End holds (red)
display(usage_bytype[:,:,1])  # Start holds (green)
display(usage_bytype[:,:,2])  # Intermediate holds (blue)
display(usage_bytype[:,:,3])  # Not-used holds

array([[0.06817148, 0.04993876, 0.05984252, 0.16920385, 0.20262468, 0.        , 0.18369204, 0.05658793, 0.11867017, 0.        , 0.09126859],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.   

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.

array([[0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.0073351 , 0.        , 0.        , 0.01409393, 0.        , 0.        , 0.        , 0.        ],
       [0.00194939, 0.01117696, 0.00228377, 0.00685843, 0.01807096, 0.00481655, 0.0041051 , 0.01257853, 0.01213031, 0.00441814, 0.00286005],
       [0.00064742, 0.00463157, 0.00877936, 0.01684014, 0.0303151 , 0.01376666, 0.01156115, 0.00254701, 0.00517939, 0.        , 0.        ],
       [0.00610428, 0.        , 0.00563472, 0.00466003, 0.01083546, 0.01713184, 0.013105  , 0.01096352, 0.02054682, 0.00273199, 0.00462446],
       [0.00220551, 0.0049375 , 0.02301557, 0.00602602, 0.02011995, 0.00969713, 0.02803133, 0.00570587, 0.00538572, 0.0050869 , 0.00115256],
       [0.00220551, 0.00231223, 0.00593354, 0.00903548, 0.01717453, 0.00744894, 0.00493038, 0.00891453, 0.00937698, 0.00359285, 0.00170038],
       [0.001

array([[0.00488213, 0.00498123, 0.0049274 , 0.00433297, 0.00415131, 0.00525267, 0.00425422, 0.00494509, 0.00460765, 0.00525267, 0.00475659],
       [0.00525267, 0.00525267, 0.00525267, 0.00505656, 0.00525267, 0.00525267, 0.00487585, 0.00525267, 0.00525267, 0.00525267, 0.00525267],
       [0.00520056, 0.00495384, 0.00519161, 0.0050693 , 0.00476952, 0.0051239 , 0.00514292, 0.00491637, 0.00492835, 0.00513455, 0.00517621],
       [0.00523537, 0.00512884, 0.00501795, 0.00480243, 0.00444216, 0.0048846 , 0.00494357, 0.00518458, 0.0051142 , 0.00525267, 0.00525267],
       [0.00508947, 0.00525267, 0.00510202, 0.00512808, 0.00496297, 0.00479463, 0.00490229, 0.00495955, 0.00470333, 0.00517963, 0.00512903],
       [0.00519371, 0.00512066, 0.00463732, 0.00509156, 0.00471474, 0.00499341, 0.00450322, 0.00510012, 0.00510868, 0.00511667, 0.00522186],
       [0.00519371, 0.00519085, 0.00509403, 0.0050111 , 0.00479349, 0.00505352, 0.00512085, 0.00501433, 0.00500197, 0.00515661, 0.00520721],
       [0.005

In [23]:
counts

array([[1948, 1427, 1710, 4835, 5790,    0, 5249, 1617, 3391,    0, 2608],
       [   0,    0,    0, 1031,    0,    0, 1981,    0,    0,    0,    0],
       [ 274, 1571,  321,  964, 2540,  677,  577, 1768, 1705,  621,  402],
       [  91,  651, 1234, 2367, 4261, 1935, 1625,  358,  728,    0,    0],
       [ 858,    0,  792,  655, 1523, 2408, 1842, 1541, 2888,  384,  650],
       [ 310,  694, 3235,  847, 2828, 1363, 3940,  802,  757,  715,  162],
       [ 310,  325,  834, 1270, 2414, 1047,  693, 1253, 1318,  505,  239],
       [ 171, 1074,  420, 1062, 1371, 2092,  999, 2358,  792,  323,  700],
       [ 306, 1209, 1737, 1884, 3347, 2035,  842, 4687, 1509,  731,  416],
       [ 846,  698,  745,  992, 1063, 1178, 2739, 1379,  545,  538,  924],
       [   0, 1099, 1088,  717, 3730,  730, 2806, 2179,  449, 2549,  585],
       [   0,  548, 1660,  540, 1180, 1251,  681,  394,  445,  767,  523],
       [   1,  866,  282, 1075, 2074,  817, 1306,    0,  920,  207,  536],
       [2124,    0, 1875,

In [33]:
usage = counts.astype(np.float32) / np.sum(usage)
display(usage)

array([[3.70268300e-02, 2.71238629e-02, 3.25030163e-02, 9.19018090e-02, 1.10054076e-01, 0.00000000e+00, 9.97709557e-02, 3.07353102e-02, 6.44548163e-02, 0.00000000e+00, 4.95718531e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.95968486e-02, 0.00000000e+00, 0.00000000e+00, 3.76540795e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.20808576e-03, 2.98609585e-02, 6.10144343e-03, 1.83233377e-02, 4.82793376e-02, 1.28681539e-02, 1.09673925e-02, 3.36054601e-02, 3.24079804e-02, 1.18037276e-02, 7.64106028e-03],
       [1.72969280e-03, 1.23739559e-02, 2.34553944e-02, 4.49910201e-02, 8.09914395e-02, 3.67797315e-02, 3.08873709e-02, 6.80472516e-03, 1.38375424e-02, 0.00000000e+00, 0.00000000e+00],
       [1.63085312e-02, 0.00000000e+00, 1.50540294e-02, 1.24499863e-02, 2.89485939e-02, 4.57703322e-02, 3.50120217e-02, 2.92907301e-02, 5.48939854e-02, 7.29892310e-03, 1.23549486e-02],
       [5.89236012e-03, 1.31912827e-02, 6.14896268e-02, 1.60994474e-02, 5.3

In [ ]:
#xs  = np.arange(start=93, stop=93+50*11, step=50)
#ys = np.arange(start=937, stop=937+-50*11, step=-50)

# im = Image.open('mb2016.png').convert('RGBA')
# bg = Image.new('RGBA', im.size, (255,255,255,0))
# draw = ImageDraw.Draw(bg)
# draw.ellipse([93-10+150, 937-10, 93+10+150, 937+10], fill=(0, 255, 0, 50))
# Image.alpha_composite(im, bg).show()